Whisper
AznamirWoW/PallyPower pull request #5
Opened 2022-04-16 21:30 UTC by icyz

set normal bless using whispering e.g. "/w paladin !BOK" will set Bless of King for the player who whisp

2022-04-16 21:49 UTC, Treeston requested changes

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +-- set normal bless using whispering e.g. "/w paladin !BOK" will set Bless of King for the player who whisp
also add a message filter (cf. [`ChatFrame_AddMessageEventFilter`](https://wowpedia.fandom.com/wiki/API_ChatFrame_AddMessageEventFilter)) to hide these whispers and the auto-replies

2022-04-16 21:49 UTC, Treeston commented on PallyPowerValues.lua
> +}
Do not hardcode names.

PallyPower is used by players around the globe. Optimally, you would use spell links (cf. [`GetSpellLink`](https://wowpedia.fandom.com/wiki/API_GetSpellLink)), which will even be clickable by players in mismatched locales. At minimum, use the correct spell name for the current locale (cf. `PallyPower.Spells` and `PallyPower.GSpells`)

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +                            SendChatMessage(pally .. " -> " .. PallyPower.IDToBless[PallyPower_Assignments[pally][PallyPower.ClassToID[englishClass]]] .. normalBlessText, "WHISPER", "Common", playerN
`arg3 = nil` for default language, don't hardcode `Common`, this won't work for horde

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +                            SendChatMessage(pally .. " -> " .. PallyPower.IDToBless[PallyPower_Assignments[pally][PallyPower.ClassToID[englishClass]]] .. normalBlessText, "WHISPER", "Common", playerN
also do we need a separate chat message for each paladin in the raid? concatenate this into a single reply, otherwise you'll quickly get spam filtered if many raiders use this (and you have lots of paladins in vanilla)

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +                            SendChatMessage(pally .. " -> " .. PallyPower.IDToBless[PallyPower_Assignments[pally][PallyPower.ClassToID[englishClass]]] .. normalBlessText, "WHISPER", "Common", playerN
also this line of code is very unreadable, split it up

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +                local localizedClass, englishClass, localizedRace, englishRace, sex, playerName, realm = GetPlayerInfoByGUID(playerGuid)
we almost definitely already have this data somewhere; check the roster functions

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +        if sfind(text, "!WISDOM") then
use `text:find("^%s*!WISDOM")` to only match at start of string

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +        if sfind(text, "!WISDOM") then
also localization concerns once again, what about players not playing in english?

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +            blessID = 99
yeah, no; find a clean way to handle this special case that doesn't involve a magic blessing id

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +        if blessID > 0 then
just `return` out

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +                            -- self:Print(PallyPower_Assignments[pally][PallyPower.ClassToID[englishClass]])
get rid of your debug comments please

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +                SendChatMessage("You have now assigned " .. blessName .. " bless (small)", "WHISPER", "Common", playerName)
same as before, don't hardcode arg3

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +                SendChatMessage("You have now assigned " .. blessName .. " bless (small)", "WHISPER", "Common", playerName)
also localization concerns here

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +                self:Print("Player not found. Is he/she in your group?")
if a player is shown this message, what are they supposed to do about it?

either silently discard or error reply to the sender, don't show anything to user

2022-04-16 21:49 UTC, Treeston commented on PallyPower.lua
> +    if text then
text cannot be nil

2022-07-20 07:25 UTC, Slivo-fr commented
I'm skeptical about this, there will be loads of raiders that will ask the wrong pally to switch assignment or override intended blessing by the raid leaders. 
For example I don't want my warrior to **silently** self remove their salvation for BOK or AP.

2022-07-20 15:31 UTC, Treeston commented
well, tying it to the existing free assign switch would solve that problem

2025-01-29 18:31 UTC, closed without merging